file_format: "1"
id: corne_with_dongle
name: Corne with dongle
type: shield
url: https://github.com/foostan/crkbd/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - corne_with_dongle_left
  - corne_with_dongle_right
  - corne_with_dongle_central